# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: double-quote-string-fixer

-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args: ["--skip-string-normalization"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    -   id: mypy
        additional_dependencies: ["types-PyYAML"]

-   repo: https://github.com/espressif/check-copyright/
    rev: v1.0.1
    hooks:
    -   id: check-copyright
        args: ['--config', '.copyright-config.yaml']
